### ISSUE TITLE
How to programatically add a plan to an user

### ISSUE THREAD

**Issue by rafael-figueiredogluz** [InspiryThemes/inspiry-memberships#3]
Hi,

I need to add a plan to a user without a payment. Can you guys send me a tip to how to do this?

I'm using this function below:
$ims_membership_method->add_user_membership($plano2_id, $user->ID, $vendor);

But when I check with this other function:
$r = $ims_membership_method->user_has_membership($user->ID);
var_dump($r); //returns null

I check the sqls tables but I can't find the tables created. It's needed to run a function to create this tables first? Where I'm missing?

Thanks!

**Comment by saqibsarwar** [comment]
Good to know that you have sorted it out.
